const express=require('express'),cors=require('cors'),crypto=require('crypto'),{Pool}=require('pg');
const app=express(),pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false});
const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD,TOKEN_SECRET=process.env.TOKEN_SECRET;app.use(express.json({limit:'1mb'}));app.use(cors({origin:(process.env.ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()).filter(Boolean)}));
const statuses=['접수','입금 완료','발송 완료','배송 완료'];const sign=s=>crypto.createHmac('sha256',TOKEN_SECRET).update(s).digest('hex');function issue(){const p=Buffer.from(JSON.stringify({exp:Date.now()+8*3600000})).toString('base64url');return p+'.'+sign(p)}function admin(req,res,next){const t=(req.headers.authorization||'').replace('Bearer ','');const [p,s]=t.split('.');try{if(!p||!crypto.timingSafeEqual(Buffer.from(s||''),Buffer.from(sign(p)))||JSON.parse(Buffer.from(p,'base64url')).exp<Date.now())throw 0;next()}catch{return res.status(401).json({message:'관리자 인증이 필요합니다.'})}}
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS products(id text primary key,name text not null,fruit_count text not null,price integer not null);CREATE TABLE IF NOT EXISTS orders(id uuid primary key,order_number text unique not null,created_at timestamptz default now(),orderer_name text not null,orderer_phone text not null,receiver_name text not null,receiver_phone text not null,postcode text not null,base_address text not null,detail_address text not null,memo text default '',total integer not null,status text default '접수');CREATE TABLE IF NOT EXISTS order_items(id bigserial primary key,order_id uuid references orders(id) on delete cascade,product_id text,name text,fruit_count text,unit_price integer,quantity integer);`);await pool.query(`INSERT INTO products VALUES ('xl','특대과','9~11과',55000),('large','대과','12~14과',45000),('medium','중과','15~18과',39000) ON CONFLICT DO NOTHING`)}
app.get('/api/health',(q,s)=>s.json({ok:true}));app.get('/api/products',async(q,s)=>s.json({products:(await pool.query('SELECT * FROM products ORDER BY CASE id WHEN \'xl\' THEN 1 WHEN \'large\' THEN 2 ELSE 3 END')).rows}));
app.post('/api/orders',async(req,res)=>{const b=req.body,phone=/^01[016789]-\d{3,4}-\d{4}$/;if(!b.ordererName||!b.receiverName||!phone.test(b.ordererPhone)||!phone.test(b.receiverPhone)||!b.postcode||!b.baseAddress||!b.detailAddress||!Array.isArray(b.items)||!b.items.length)return res.status(400).json({message:'주문 정보를 확인해주세요.'});const ids=b.items.map(i=>i.productId),ps=(await pool.query('SELECT * FROM products WHERE id=ANY($1)',[ids])).rows;if(ps.length!==new Set(ids).size)return res.status(400).json({message:'상품 정보가 올바르지 않습니다.'});let total=0;for(const i of b.items){if(!Number.isInteger(i.quantity)||i.quantity<1||i.quantity>20)return res.status(400).json({message:'수량을 확인해주세요.'});total+=ps.find(p=>p.id===i.productId).price*i.quantity}const id=crypto.randomUUID(),orderNumber='DY'+new Date().toISOString().slice(2,10).replace(/-/g,'')+crypto.randomInt(1000,9999),c=await pool.connect();try{await c.query('BEGIN');await c.query('INSERT INTO orders(id,order_number,orderer_name,orderer_phone,receiver_name,receiver_phone,postcode,base_address,detail_address,memo,total) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)',[id,orderNumber,b.ordererName,b.ordererPhone,b.receiverName,b.receiverPhone,b.postcode,b.baseAddress,b.detailAddress,b.memo||'',total]);for(const i of b.items){const p=ps.find(x=>x.id===i.productId);await c.query('INSERT INTO order_items(order_id,product_id,name,fruit_count,unit_price,quantity) VALUES($1,$2,$3,$4,$5,$6)',[id,p.id,p.name,p.fruit_count,p.price,i.quantity])}await c.query('COMMIT');res.status(201).json({orderNumber,total})}catch(e){await c.query('ROLLBACK');res.status(500).json({message:'주문 저장에 실패했습니다.'})}finally{c.release()}});
const orderSelect=`SELECT o.*,COALESCE(json_agg(json_build_object('name',i.name,'fruit_count',i.fruit_count,'unit_price',i.unit_price,'quantity',i.quantity)) FILTER(WHERE i.id IS NOT NULL),'[]') items FROM orders o LEFT JOIN order_items i ON i.order_id=o.id`;
app.post('/api/orders/lookup',async(req,res)=>{const {orderNumber,ordererName,ordererPhone}=req.body,r=await pool.query(orderSelect+' WHERE o.order_number=$1 AND o.orderer_name=$2 AND o.orderer_phone=$3 GROUP BY o.id',[orderNumber,ordererName,ordererPhone]);if(!r.rows[0])return res.status(404).json({message:'일치하는 주문을 찾지 못했습니다.'});res.json({order:r.rows[0]})});
app.post('/api/admin/login',(req,res)=>{if(!ADMIN_PASSWORD||req.body.password!==ADMIN_PASSWORD)return res.status(401).json({message:'비밀번호가 올바르지 않습니다.'});res.json({token:issue()})});app.get('/api/admin/orders',admin,async(q,s)=>s.json({orders:(await pool.query(orderSelect+' GROUP BY o.id ORDER BY o.created_at DESC')).rows}));app.patch('/api/admin/orders/:id/status',admin,async(req,res)=>{if(!statuses.includes(req.body.status))return res.status(400).json({message:'상태가 올바르지 않습니다.'});await pool.query('UPDATE orders SET status=$1 WHERE id=$2',[req.body.status,req.params.id]);res.json({ok:true})});app.put('/api/admin/products',admin,async(req,res)=>{for(const p of req.body.prices||[])if(Number.isInteger(p.price)&&p.price>=0)await pool.query('UPDATE products SET price=$1 WHERE id=$2',[p.price,p.id]);res.json({ok:true})});app.post('/api/admin/orders/delete',admin,async(req,res)=>{if(req.body.password!==ADMIN_PASSWORD)return res.status(401).json({message:'관리자 비밀번호가 올바르지 않습니다.'});await pool.query('DELETE FROM orders WHERE id=ANY($1::uuid[])',[req.body.ids||[]]);res.json({ok:true})});
const csv=v=>'"'+String(v??'').replace(/"/g,'""')+'"';app.get('/api/admin/orders.csv',admin,async(req,res)=>{const rows=(await pool.query(orderSelect+' GROUP BY o.id ORDER BY o.created_at DESC')).rows,head=['주문번호','주문일시','주문자','연락처','상품','금액','상태','받는분','받는분연락처','주소','메모'];const body=rows.map(o=>[o.order_number,o.created_at,o.orderer_name,o.orderer_phone,o.items.map(i=>`${i.name}x${i.quantity}`).join(' / '),o.total,o.status,o.receiver_name,o.receiver_phone,`(${o.postcode}) ${o.base_address} ${o.detail_address}`,o.memo].map(csv).join(','));res.type('text/csv').set('Content-Disposition','attachment; filename="daeyun-orders.csv"').send('\ufeff'+[head.join(','),...body].join('\n'))});
init().then(()=>app.listen(process.env.PORT||3000,()=>console.log('Daeyun API ready'))).catch(e=>{console.error(e);process.exit(1)});
